spring.application.name=monkey-ams-web
app.id=monkey-ams-web
server.port=8081
apollo.meta=http://apollo-configservice:8080
# 直接指定 ConfigService，避免拿到 Docker 内网 IP
apollo.config-service=http://apollo-configservice:8080
apollo.bootstrap.enabled=true
apollo.bootstrap.eagerLoad.enabled=true
